"use client";

import { useRef, useState, type FormEvent } from "react";
import { CalendarDays, Check, ChevronRight, Clock3, FilePenLine, MapPin, Plus, Radio, Save, ShieldCheck, Trash2 } from "lucide-react";
import { useAuth } from "@/presentation/providers/auth-provider";
import { useEvents } from "@/presentation/providers/events-provider";
import { DEMO_DATE, roads } from "@/data/catalog/demo-data";
import type { CeremonyEvent, Closure } from "@/domain/entities/ceremony-event";
import { formatDate } from "@/domain/formatters/format-date";
import { RoadMap } from "@/presentation/components/road-map";
import { AdminRoadPicker } from "@/presentation/components/admin-road-picker";
import type { RoadSegment } from "@/domain/entities/road-segment";
import { useTranslation } from "@/presentation/i18n/translation-provider";

export default function DashboardPage() {
  const { user } = useAuth();
  const { events, ready, saveEvent, togglePublished, deleteEvent } = useEvents();
  const { locale, t } = useTranslation();
  const d = t.dashboard;
  const [editing, setEditing] = useState<string | null>(null), [name, setName] = useState(""), [date, setDate] = useState(DEMO_DATE), [start, setStart] = useState("10:00"), [end, setEnd] = useState("15:00"), [closure, setClosure] = useState<Closure>("Tutup Total"), [roadId, setRoadId] = useState(roads[0].id), [meaning, setMeaning] = useState(""), [message, setMessage] = useState(""), [error, setError] = useState(""), [filter, setFilter] = useState<"all" | "published" | "draft">("all"), [deleting, setDeleting] = useState<string | null>(null), [segments, setSegments] = useState<RoadSegment[]>([]);
  const nameInput = useRef<HTMLInputElement>(null);
  const owned = events.filter((event) => event.banjarId === user?.banjarId);
  const visible = owned.filter((event) => filter === "all" || (filter === "published" ? event.published : !event.published));
  const selectedRoad = roads.find((road) => road.id === roadId)!;
  function reset() { setEditing(null); setName(""); setDate(DEMO_DATE); setStart("10:00"); setEnd("15:00"); setClosure("Tutup Total"); setRoadId(roads[0].id); setMeaning(""); setError(""); setSegments([]); }
  function edit(event: CeremonyEvent) { setEditing(event.id); setName(event.name); setDate(event.date); setStart(event.startTime); setEnd(event.endTime); setClosure(event.closure); setRoadId(event.roadId); setMeaning(event.meaning); setError(""); setMessage(""); nameInput.current?.focus(); }
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setMessage(""); if (!user) return;
    if (!name.trim()) { setError(d.invalidName); return; }
    if (start >= end) { setError(d.invalidTime); return; }
    const existing = owned.find((item) => item.id === editing);
    const eventId = editing ?? crypto.randomUUID();
    const saved = saveEvent({ id: eventId, name: name.trim(), date, startTime: start, endTime: end, closure, roadId, meaning: meaning.trim(), banjarId: user.banjarId, banjar: user.banjar, published: existing?.published ?? false });
    if (saved) {
      // Output array segmen jalan (Leaflet + OSRM) disimpan sebagai dummy lokal per agenda.
      // Nantinya array ini yang dikirim ke backend/PostGIS bersama payload event.
      try { sessionStorage.setItem(`balepath:segments:${eventId}`, JSON.stringify(segments)); } catch { /* abaikan kuota storage */ }
      setMessage(`${editing ? d.saveSuccess : d.draftSuccess} (${segments.length} segmen jalan tersimpan.)`);
      reset();
    } else setError(d.saveError);
  }
  if (!ready) return <div className="loading-screen" role="status">{t.common.loading}</div>;
  return <>
    <div className="breadcrumb">{d.breadcrumbPortal} <ChevronRight size={14} /> {d.breadcrumbDashboard}</div>
    <section className="admin-welcome"><div><p className="eyebrow"><span className="poleng" /> {user?.banjar}</p><h1>{d.welcome}<br /><em>{d.welcomeEmphasis}</em></h1><p className="muted">{d.welcomeText}<br />{d.welcomeText2}</p></div><div className="welcome-aside"><span className="badge demo-badge"><ShieldCheck size={14} /> {d.demoMode}</span><p><CalendarDays size={16} /> {formatDate(DEMO_DATE, locale)}</p><small>{d.dummySchedule}</small></div></section>
    <section className="stats-grid" aria-label={d.summary}><div className="stat-card"><span className="stat-icon"><CalendarDays size={22} /></span><div><span className="muted">{d.total}</span><strong>{owned.length.toString().padStart(2, "0")}</strong></div><small>{d.totalHelp}</small></div><div className="stat-card"><span className="stat-icon green"><Radio size={22} /></span><div><span className="muted">{d.published}</span><strong>{owned.filter((event) => event.published).length.toString().padStart(2, "0")}</strong></div><small>{d.publishedHelp}</small></div><div className="stat-card"><span className="stat-icon clay"><FilePenLine size={22} /></span><div><span className="muted">{d.drafts}</span><strong>{owned.filter((event) => !event.published).length.toString().padStart(2, "0")}</strong></div><small>{d.draftsHelp}</small></div></section>
    <div className="section-title"><div><p className="eyebrow">{d.workspace}</p><h2>{d.planTitle}</h2></div><span className="muted small">{d.steps} <ChevronRight size={13} /> {d.step2} <ChevronRight size={13} /> {d.step3}</span></div>
    <div className="admin-workspace"><section className="panel event-editor"><div className="section-title"><h3><FilePenLine size={20} /> {editing ? d.editTitle : d.newTitle}</h3>{editing && <button className="text-button" onClick={reset}>{d.cancelEdit}</button>}</div><p className="muted small">{d.clearInfo}</p><form className="stack" onSubmit={submit}><label>{d.ceremonyName}<input ref={nameInput} required maxLength={120} value={name} onChange={(e) => setName(e.target.value)} placeholder={d.ceremonyPlaceholder} /></label><label>{d.eventDate}<input type="date" required value={date} onChange={(e) => setDate(e.target.value)} /></label><div className="form-grid"><label>{d.startTime}<input type="time" required value={start} onChange={(e) => setStart(e.target.value)} /></label><label>{d.endTime}<input type="time" required value={end} onChange={(e) => setEnd(e.target.value)} /></label></div><fieldset><legend>{d.closureStatus}</legend><div className="closure-options">{(["Tutup Total", "Buka-Tutup"] as Closure[]).map((value) => <label key={value} className={closure === value ? "chosen" : ""}><input type="radio" name="closure" value={value} checked={closure === value} onChange={() => setClosure(value)} /><span className={`dot ${value === "Tutup Total" ? "red" : "gold"}`} />{t.closure[value]}</label>)}</div></fieldset><label>{d.road}<select value={roadId} onChange={(e) => setRoadId(e.target.value)}>{roads.map((road) => <option key={road.id} value={road.id}>{road.name}</option>)}</select></label><label>{d.meaning} <span className="muted">({d.optional})</span><textarea rows={3} maxLength={600} value={meaning} onChange={(e) => setMeaning(e.target.value)} placeholder={d.meaningPlaceholder} /></label>{error && <p role="alert" className="error-message">{error}</p>}<p className="muted small" aria-live="polite">{segments.length === 0 ? "Belum ada segmen jalan dari peta interaktif." : `${segments.length} segmen jalan dari peta interaktif akan disimpan bersama agenda ini.`}</p><button type="submit" className="button primary"><Save size={17} />{editing ? d.save : d.saveDraft}</button><p className="muted small">{editing ? d.statusKept : d.draftHidden}</p></form></section>
    <section className="panel spatial-editor"><div className="section-title"><div><h3><MapPin size={20} /> {d.mapMarking}</h3><p className="eyebrow">{d.mapInstruction}</p></div><span className={`badge ${closure === "Tutup Total" ? "full" : "partial"}`}>{t.closure[closure]}</span></div><RoadMap events={[{ id: "preview", name, date, startTime: start, endTime: end, closure, roadId, banjarId: user!.banjarId, banjar: user!.banjar, published: false, meaning }]} selectedRoadId={roadId} onSelectRoad={setRoadId} /><div className="interactive-road-picker"><div className="section-title"><h3><MapPin size={20} /> Penandaan ruas jalan interaktif (Ubud, Bali)</h3></div><AdminRoadPicker segments={segments} onSegmentsChange={setSegments} /><p className="muted small">{segments.length} segmen jalan akan disimpan bersama draf ini.</p></div><div className="selected-road"><span className="stat-icon"><MapPin size={20} /></span><div><small className="eyebrow">{d.selectedSegment}</small><strong>{selectedRoad.name}</strong><span className="muted small">{selectedRoad.coordinates.map((point) => point.map((n) => n.toFixed(4)).join(", ")).join(" → ")}</span></div><Check size={20} /></div><div className="notice"><ShieldCheck size={19} /><p>{d.geometryNote}</p></div></section></div>
    <section className="agenda-managed"><div className="section-title"><div><p className="eyebrow">{d.coordination}</p><h2>{d.managedTitle}</h2><p className="muted small">{d.managedOnly}</p></div><label className="filter-label"><span className="sr-only">{d.publicationFilter}</span><select value={filter} onChange={(e) => setFilter(e.target.value as typeof filter)}>{Object.entries(d.filters).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>{message && <p className="success-message" role="status"><Check size={18} />{message}</p>}<div className="managed-list">{visible.length === 0 ? <div className="panel empty-state"><CalendarDays size={32} /><h3>{d.empty}</h3><button className="button secondary" onClick={() => { reset(); nameInput.current?.focus(); }}><Plus size={16} /> {d.create}</button></div> : visible.map((event) => <article className="managed-event" key={event.id}><div><span className={`badge ${event.closure === "Tutup Total" ? "full" : "partial"}`}>{t.closure[event.closure]}</span><h3>{event.name}</h3><p className="muted small"><MapPin size={14} />{roads.find((road) => road.id === event.roadId)?.name}</p></div><div className="event-schedule"><strong>{formatDate(event.date, locale)}</strong><span><Clock3 size={14} /> {event.startTime} – {event.endTime} WITA</span><span className={`publication-status ${event.published ? "published" : ""}`}>{event.published ? d.published : d.draftStatus}</span></div><div className="event-actions"><button className={`button ${event.published ? "secondary" : "primary"}`} onClick={() => { togglePublished(event.id); setMessage(event.published ? d.unpublishedSuccess : d.publishedSuccess); }}><Radio size={16} />{event.published ? d.unpublish : d.publish}</button><div className="row"><button className="button secondary" aria-label={`${d.edit} ${event.name}`} onClick={() => edit(event)}><FilePenLine size={15} /> {d.edit}</button><button className="icon-button danger" aria-label={`${d.delete} ${event.name}`} onClick={() => setDeleting(event.id)}><Trash2 size={16} /></button></div>{deleting === event.id && <div className="delete-confirm" role="group" aria-label={d.deleteConfirm}><p>{d.deleteQuestion}</p><button className="button secondary" onClick={() => setDeleting(null)}>{d.cancel}</button><button className="button danger" onClick={() => { deleteEvent(event.id); if (editing === event.id) reset(); setDeleting(null); setMessage(d.deletedSuccess); }}>{d.confirmDelete}</button></div>}</div></article>)}</div></section>
  </>;
}
