"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, CalendarDays, Clock3, Flower2, Info, MapPin, Search, SlidersHorizontal, X } from "lucide-react";
import { useEvents } from "@/presentation/providers/events-provider";
import { DEMO_DATE, roads } from "@/data/catalog/demo-data";
import { formatDate } from "@/domain/formatters/format-date";
import { RoadMap } from "@/presentation/components/road-map";
import { localePath } from "@/presentation/i18n/locale";
import { useTranslation } from "@/presentation/i18n/translation-provider";

export default function PublicMapPage() {
  const { events, ready } = useEvents();
  const { locale, t } = useTranslation();
  const [query, setQuery] = useState("");
  const [date, setDate] = useState(DEMO_DATE);
  const [closure, setClosure] = useState("all");
  const [selectedId, setSelectedId] = useState<string>();
  const [roadId, setRoadId] = useState<string>();
  const published = ready ? events.filter((event) => event.published) : [];
  const filters = [{ value: "all", label: t.map.filterAll }, { value: "Tutup Total", label: t.closure["Tutup Total"] }, { value: "Buka-Tutup", label: t.closure["Buka-Tutup"] }];
  const filtered = published.filter((event) => { const road = roads.find((item) => item.id === event.roadId); return (!date || event.date === date) && (closure === "all" || event.closure === closure) && `${event.name} ${event.banjar} ${road?.name ?? ""}`.toLocaleLowerCase(locale).includes(query.trim().toLocaleLowerCase(locale)); }).sort((a, b) => `${a.date}${a.startTime}`.localeCompare(`${b.date}${b.startTime}`));
  const selected = filtered.find((event) => event.id === selectedId && (!roadId || event.roadId === roadId)) ?? filtered.find((event) => !roadId || event.roadId === roadId);
  const selectedRoad = roads.find((road) => road.id === (roadId ?? selected?.roadId));
  function resetFilters() { setQuery(""); setDate(DEMO_DATE); setClosure("all"); setRoadId(undefined); setSelectedId(undefined); }
  return <div className="public-container">
    <section className="public-intro"><div><p className="public-eyebrow"><span className="public-tiny-diamond" /> {t.map.eyebrow}</p><h1>{t.map.heroTitle}<br className="public-mobile-break" /> <em>{t.map.heroTitleEmphasis}</em></h1><p className="public-lead">{t.map.lead}</p></div><div className="public-location"><MapPin size={19} aria-hidden="true" /><div><strong>{t.map.locationCity}</strong><span>{t.map.locationCountry}</span></div></div></section>
    <div className="public-map-toolbar"><label className="public-search"><Search size={18} aria-hidden="true" /><span className="public-sr-only">{t.map.searchLabel}</span><input type="search" placeholder={t.map.searchPlaceholder} value={query} onChange={(e) => { setQuery(e.target.value); setRoadId(undefined); }} /></label><label className="public-date-field"><CalendarDays size={17} aria-hidden="true" /><span className="public-sr-only">{t.map.dateLabel}</span><input aria-label={t.map.dateLabel} type="date" value={date} onChange={(e) => { setDate(e.target.value); setRoadId(undefined); }} /></label><div className="public-filter-group" aria-label={t.map.filterLabel}><SlidersHorizontal size={16} aria-hidden="true" />{filters.map(({ value, label }) => <button key={value} type="button" aria-pressed={closure === value} onClick={() => { setClosure(value); setRoadId(undefined); }}>{label}</button>)}</div></div>
    <div className="public-workspace"><div className="public-map-column"><div className="public-section-bar"><h2><span className="public-gold">01</span> {t.map.mapTitle}</h2><span className="public-demo-label">{t.map.demoMode}</span></div><RoadMap events={filtered} selectedRoadId={roadId ?? selected?.roadId} onSelectRoad={(id) => { setRoadId(id); setSelectedId(undefined); }} /><div className="public-map-note"><Info size={17} aria-hidden="true" /><p>{t.map.scheduleNote} <strong>{date ? formatDate(date, locale) : t.map.allDates}</strong>. {t.map.followInfo}</p></div></div>
      <aside className="public-side" aria-label={t.map.detailTitle}><div className="public-section-bar"><h2><span className="public-gold">02</span> {t.map.detailTitle}</h2><Flower2 size={17} className="public-gold" aria-hidden="true" /></div><div className="public-detail-card" aria-live="polite"><div className="public-poleng-trim" />{!ready ? <div className="public-empty" role="status">{t.map.preparing}</div> : selected ? <div className="public-detail-body"><div className="public-between"><span className={`public-status ${selected.closure === "Tutup Total" ? "public-full" : "public-partial"}`}>{t.closure[selected.closure]}</span><span className="public-small-label">{t.map.scheduleLabel}</span></div><h3>{selected.name}</h3><p className="public-icon-line"><MapPin size={16} aria-hidden="true" />{selected.banjar}</p><div className="public-detail-time"><Clock3 size={20} aria-hidden="true" /><div><strong>{selected.startTime} – {selected.endTime} <small>WITA</small></strong><span>{formatDate(selected.date, locale)}</span></div></div><div className="public-road-detail"><span className="public-small-label">{t.map.affectedRoad}</span><strong>{roads.find((road) => road.id === selected.roadId)?.name ?? t.map.roadUnavailable}</strong></div><div className="public-meaning"><h4><Flower2 size={18} aria-hidden="true" /> {t.map.meaningTitle}</h4><p>{selected.meaning || t.map.meaningMissing}</p></div><p className="public-etiquette">{t.map.etiquette}</p><Link href={`${localePath("/kalender", locale)}?date=${selected.date}`} className="public-action public-action-gold">{t.map.calendarLink} <ArrowRight size={17} aria-hidden="true" /></Link></div> : <div className="public-empty"><Flower2 size={32} aria-hidden="true" /><h3>{selectedRoad ? selectedRoad.name : t.map.noSchedule}</h3><p>{t.map.noMatch}</p><button type="button" className="public-action" onClick={resetFilters}>{t.map.reset}</button></div>}</div><div className="public-small-note"><span className="public-tiny-diamond" /><p>{t.map.journeyNote}</p></div></aside></div>
    <section className="public-agenda-section" aria-labelledby="agenda-title"><div className="public-section-bar"><div><p className="public-eyebrow">{t.map.agendaEyebrow}</p><h2 id="agenda-title" className="public-serif-title">{t.map.agendaSelected} <span className="public-count">{filtered.length}</span></h2></div><Link href={localePath("/kalender", locale)} className="public-text-link">{t.map.fullCalendar} <ArrowRight size={16} aria-hidden="true" /></Link></div>{!ready ? <p role="status" className="public-empty">{t.map.loadingAgenda}</p> : !filtered.length ? <div className="public-no-results"><Search size={22} aria-hidden="true" /><p>{t.map.noResults}</p><button type="button" onClick={resetFilters} className="public-action"><X size={16} aria-hidden="true" /> {t.map.resetFilter}</button></div> : <div className="public-agenda-grid">{filtered.map((event) => <button type="button" key={event.id} className="public-agenda-card" aria-pressed={selected?.id === event.id} onClick={() => { setSelectedId(event.id); setRoadId(event.roadId); }}><span className="public-between"><span className={`public-status ${event.closure === "Tutup Total" ? "public-full" : "public-partial"}`}>{t.closure[event.closure]}</span><ArrowRight size={17} aria-hidden="true" /></span><strong className="public-agenda-name">{event.name}</strong><span className="public-icon-line"><MapPin size={14} aria-hidden="true" />{event.banjar}</span><span className="public-agenda-bottom"><span>{formatDate(event.date, locale)}</span><span>{event.startTime} – {event.endTime} WITA</span></span></button>)}</div>}</section>
    <section className="public-harmony"><Flower2 size={30} strokeWidth={1} aria-hidden="true" /><div><h2>{t.map.harmonyTitle}</h2><p>{t.map.harmonyText}</p></div><span className="public-small-label">{t.map.harmonyLabel}</span></section>
  </div>;
}
